### ISSUE TITLE
Some issue with the website

### ISSUE THREAD

**Issue by Timo-Breumelhof** [dyne/dynebolic#1]
Sorry, if this is the wrong place to post this.. but I noticed some things on you website that would be good to correct IMO.

I noticed that this page is ranked highest in Google: https://dyne.org/software/dynebolic/

That looks like an old page? I would create a redirect rule to: http://dyne.org/dynebolic/ I think..
I suspect that's the "new" page?

Also there is no http > https redirect, which would also be better IMO.

And lastly when you do visit https://dyne.org/dynebolic/ nearly all linked resources are http and not https which leads to a "the page is not secure"warning in browsers.

**Comment by Sakrecoer** [comment]
Many thanks for your input @Timo-Breumelhof ! I will address the issues ASAP!

**Comment by Sakrecoer** [comment]
Hi @Timo-Breumelhof,

Thanks again for taking the time to report these issues. I was not able to access the site without https, that redirect thing seems to work on my machine, with a blank browser.

https://dyne.org/software/dynebolic/ now redirects to https://dyne.org/dynebolic/ and it seems search engines have picked up on it.

I fixed the problem with insecure resources here:
https://github.com/dyne/dynebolic/commit/55696df91595fee1db1e2576fead39a0a1a15419

I will close this issue now. Feel free to open another one if you encounter any further issues.

Warm regards from sunny sweden,
*Setto

**Comment by Timo-Breumelhof** [comment]
ok sounds good :-)
