### ISSUE TITLE
Cron contains a nonfree example

### ISSUE THREAD

**Issue by LuxonicPhoton** [dyne/dynebolic#1]
Dynebolic 3.0.0 -beta:
Package: cron (pre-installed);

File: "/usr/share/doc/cron/copyright" which contains the licensing to many files in cron says that the example crontab2english.pl is licensed under the Artistic license, which is a nonfree license.

[https://www.gnu.org/licenses/license-list.html#ArtisticLicense](https://www.gnu.org/licenses/license-list.html#ArtisticLicense)

From: /usr/share/doc/cron/copyright: 
"Files: debian/examples/crontab2english.pl
Copyright: 2001, Sean M. Burke
License: Artistic"

**Comment by jaromil** [comment]
ACK. I confirm your findings, the file is indeed present inside d:b, inherited from debian/ubuntu. Thanks for finding out!

**Comment by vcgato29** [comment]
can anyone help me finish netsukuku worlwidr to finish the ecosystem im creating
