### ISSUE TITLE
Bootloader animation

### ISSUE THREAD

**Issue by jaromil** [dyne/dynebolic#18]
Customize a Plymouth theme to show a d:b rotating logo animation while waiting for boot.

Should be easy with a little bit of python knowledge. Docs are linked here https://wiki.gentoo.org/wiki/Plymouth/Theme_creation

**Comment by jaromil** [comment]
We ditch Plymouth and use KDE plasma boot anim, done!

**Comment by Sakrecoer** [comment]
@jaromil It's worth noting that plasma's anim is not a "boot animation". It runs arbitrarily after the login. This means that on a fast system it will give the impression of a slower boot as it inserts itself between the login and the desktop's appearance, for the period of at least one animation loop.
