### ISSUE TITLE
This repository is hosted on a platform that requires nonfree javascript

### ISSUE THREAD

**Issue by delgh1** [dyne/dynebolic#21]
Hello,

This is a freedom issue. Hosting a free software project on github, which requires nonfree javascript, is a moral compromise no one should make, and in fact will effectively deter the participation of contribution and bug reports (because you need an account to submit new issue, etc.). Furthermore, copilot will proprietarize free software, especially they don't care about GPL violation.

Please see [here](https://sfconservancy.org/GiveUpGitHub/) and (here)[https://sfconservancy.org/blog/2022/jun/30/give-up-github-launch/]

Free replacement exists, like Codeberg.org (100% free javascript, under review by GNU), essentially a github clone with a free-software-oriented philosophy. The underlying forgejo software is available for anyone to self-host. Ad: In fact, I myself host one, and it's available for public use (forgejo.jing.rocks).

**Comment by jaromil** [comment]
Good point about non free js. While dormant dynebolic was simply parked here, but now it is accepting contributions it should rely on 100% free infra. We will reorganize the repository hosting platform and update this issue and the homepage information with progresses.

**Comment by jaromil** [comment]
https://git.devuan.org/jaromil/dynebolic

this is the official repo for SDK sources now

webpage and docs will link this or the dyneIV subdir directly.
